### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/justlight_theme_options#6]
Hi Carmen, enclosed the completed German translation as .po file.

[de.po.zip](https://github.com/JustCarmen/justlight_theme_options/files/5137933/de.po.zip)

**Comment by mpwt** [comment]
Hi Carmen, there is one untranslated word in AdminTemplate.php:

`I18N::direction() === 'rtl' ? 'right' : 'left')`

It is the **%s** in "Here you can upload a logo. The logo is displayed above the tree title in the top **%s** corner of the page. Leave blank if you are not using a logo.".

**Comment by mpwt** [comment]
Hello Carmen, thank you for the corrections. Enclosed is the completed German translation.

[de.po.zip](https://github.com/JustCarmen/justlight_theme_options/files/5735165/de.po.zip)

**Comment by JustCarmen** [comment]
Thanks. Updated via f16f3f53
